import { defineEntity, defineField } from "../define";
import type { FieldFormat } from "../types";

const idField = (name: string, label: string) =>
  defineField({
    name,
    label: { en: label, de: label },
    type: "string",
    format: "uuid",
    required: true,
    primary: true,
    technical: true,
    projections: {
      list: { visible: false, sortable: false },
      form: { component: "hidden", readOnly: true },
      lookup: { searchKey: false },
      api: { exposed: false },
      ai: { description: "Technical primary key.", extractable: false },
    },
  });

const tenantField = defineField({
  name: "tenantId",
  label: { en: "Tenant", de: "Mandant" },
  type: "string",
  format: "uuid",
  required: true,
  technical: true,
  projections: {
    list: { visible: false, sortable: false },
    form: { component: "hidden", readOnly: true },
    lookup: { searchKey: false },
    api: { exposed: false },
    ai: { description: "Server-resolved tenant identifier.", extractable: false },
  },
});

const customAttributesField = defineField({
  name: "customAttributes",
  label: { en: "Custom attributes", de: "Zusatzfelder" },
  type: "json",
  required: false,
  projections: {
    list: { visible: false, sortable: false },
    form: { component: "json" },
    lookup: { searchKey: false },
    api: { exposed: true },
    ai: {
      description: "Controlled tenant-specific extension area.",
      extractable: true,
    },
  },
});

// Helper for standard string fields
const stringField = (
  name: string,
  label: string,
  required = false,
  format?: FieldFormat,
  defaultValue?: string,
) =>
  defineField({
    name,
    label: { en: label, de: label },
    type: "string",
    format,
    required,
    defaultValue,
    projections: {
      list: { visible: true, sortable: true },
      form: { component: "text" },
      lookup: { searchKey: true },
      api: { exposed: true },
      ai: { description: `${label} field.`, extractable: true },
    },
  });

// Helper for standard boolean fields
const booleanField = (name: string, label: string, defaultValue = false) =>
  defineField({
    name,
    label: { en: label, de: label },
    type: "boolean",
    required: true,
    defaultValue,
    projections: {
      list: { visible: true, sortable: true },
      form: { component: "checkbox" },
      lookup: { searchKey: false },
      api: { exposed: true },
      ai: { description: `${label} flag.`, extractable: true },
    },
  });

// Helper for standard date/timestamp fields
const dateField = (
  name: string,
  label: string,
  required = false,
  format: FieldFormat = "timestamp",
) =>
  defineField({
    name,
    label: { en: label, de: label },
    type: "date",
    format,
    required,
    projections: {
      list: { visible: true, sortable: true },
      form: { component: "date" },
      lookup: { searchKey: false },
      api: { exposed: true },
      ai: { description: `${label} timestamp.`, extractable: true },
    },
  });

// Helper for standard number fields
const numberField = (
  name: string,
  label: string,
  required = false,
  format: FieldFormat = "integer",
  defaultValue?: number,
) =>
  defineField({
    name,
    label: { en: label, de: label },
    type: "number",
    format,
    required,
    defaultValue,
    projections: {
      list: { visible: true, sortable: true },
      form: { component: "number" },
      lookup: { searchKey: false },
      api: { exposed: true },
      ai: { description: `${label} value.`, extractable: true },
    },
  });

// Helper for standard JSON fields
const jsonField = (name: string, label: string) =>
  defineField({
    name,
    label: { en: label, de: label },
    type: "json",
    required: false,
    projections: {
      list: { visible: false, sortable: false },
      form: { component: "json" },
      lookup: { searchKey: false },
      api: { exposed: true },
      ai: { description: `${label} JSON data.`, extractable: true },
    },
  });

export const addressEntity = defineEntity({
  name: "address",
  pluralName: "addresses",
  label: { en: "Address", de: "Adresse" },
  module: "masterdata",
  primaryKey: "addressId",
  tenantScoped: true,
  schemaVersion: 1,
  fields: [
    idField("addressId", "Address ID"),
    tenantField,
    stringField("addressNo", "Address no.", true, "code"),
    booleanField("isCustomer", "Is customer", false),
    booleanField("isSupplier", "Is supplier", false),
    stringField("companyName", "Company", false),
    stringField("firstName", "First name", false),
    stringField("lastName", "Last name", false),
    stringField("notiztext", "Notiztext", false),
    stringField("notiztextSourceEntity", "Notiztext source entity", false),
    stringField("notiztextSourceId", "Notiztext source ID", false, "uuid"),
    stringField("notiztextSourceField", "Notiztext source field", false),
    dateField("notiztextLinkedAt", "Notiztext linked at", false),
    dateField("notiztextOverriddenAt", "Notiztext overridden at", false),
    stringField("langtext", "Langtext", false),
    stringField("langtextSourceEntity", "Langtext source entity", false),
    stringField("langtextSourceId", "Langtext source ID", false, "uuid"),
    stringField("langtextSourceField", "Langtext source field", false),
    dateField("langtextLinkedAt", "Langtext linked at", false),
    dateField("langtextOverriddenAt", "Langtext overridden at", false),
    stringField("warntext", "Warntext", false),
    stringField("warntextSourceEntity", "Warntext source entity", false),
    stringField("warntextSourceId", "Warntext source ID", false, "uuid"),
    stringField("warntextSourceField", "Warntext source field", false),
    dateField("warntextLinkedAt", "Warntext linked at", false),
    dateField("warntextOverriddenAt", "Warntext overridden at", false),
    stringField("addressLine1", "Address line 1", true),
    stringField("addressLine2", "Address line 2", false),
    stringField("postalCode", "Postal code", true),
    stringField("city", "City", true),
    stringField("stateProvince", "State province", false),
    stringField("countryCode", "Country", true, "code", "DE"),
    stringField("vatId", "VAT ID", false),
    stringField("taxClassId", "Tax class ID", false, "uuid"),
    stringField("currencyId", "Currency ID", false),
    stringField("paymentTermId", "Payment term ID", false, "uuid"),
    dateField("archivedAt", "Archived at", false),
    customAttributesField,
    dateField("createdAt", "Created at", true),
    dateField("updatedAt", "Updated at", false),
    stringField("defaultDeliveryAddressId", "Default delivery address ID", false, "uuid"),
    stringField("searchText", "Search text", false),
    stringField("addressCategoryId", "Address category ID", false, "uuid"),
    stringField("salutation", "Salutation", false),
    stringField("phoneLandline", "Phone landline", false),
    stringField("phoneFax", "Phone fax", false),
    stringField("phoneMobile", "Phone mobile", false),
    stringField("email", "Email", false, "email"),
    stringField("homepage", "Homepage", false, "url"),
    stringField("leitwegId", "Leitweg ID", false),
    stringField("peppolId", "PEPPOL ID", false),
    jsonField("coordinates", "Coordinates"),
    stringField("agentId", "Agent ID", false, "uuid"),
    stringField("commissionRate", "Commission rate", false),
    stringField("creditRatingScore", "Credit rating score", false),
    booleanField("shopActive", "Shop active", false),
  ],
  relations: {
    contacts: { type: "many", target: "addressContact", inverseField: "addressId" },
    deliveryAddresses: { type: "many", target: "deliveryAddress", inverseField: "addressId" },
  },
  behaviors: { softDelete: { strategy: "archivedAt", field: "archivedAt" } },
  constraints: [
    {
      id: "address.uniqueAddressNo",
      message: {
        en: "Address number must be unique within the tenant.",
        de: "Adressnummer muss je Mandant eindeutig sein.",
      },
      severity: "error",
      fields: ["addressNo"],
    },
  ],
  tests: {
    crud: true,
    validationSmoke: true,
    fixture: {
      addressNo: "ADR-001",
      companyName: "Sample Customer",
      postalCode: "10115",
      city: "Berlin",
      countryCode: "DE",
      addressLine1: "Musterstraße 1",
    },
  },
});

export const articleEntity = defineEntity({
  name: "article",
  pluralName: "articles",
  label: { en: "Article", de: "Artikel" },
  module: "masterdata",
  primaryKey: "articleId",
  tenantScoped: true,
  schemaVersion: 1,
  fields: [
    idField("articleId", "Article ID"),
    tenantField,
    stringField("articleNo", "Article no.", true, "code"),
    stringField("name", "Name", true),
    stringField("notiztext", "Notiztext", false),
    stringField("langtext", "Langtext", false),
    stringField("kurzbeschreibung", "Kurzbeschreibung", false),
    stringField("warntext", "Warntext", false),
    stringField("notiztextSourceEntity", "Notiztext source entity", false),
    stringField("notiztextSourceId", "Notiztext source ID", false, "uuid"),
    stringField("notiztextSourceField", "Notiztext source field", false),
    dateField("notiztextLinkedAt", "Notiztext linked at", false),
    dateField("notiztextOverriddenAt", "Notiztext overridden at", false),
    stringField("langtextSourceEntity", "Langtext source entity", false),
    stringField("langtextSourceId", "Langtext source ID", false, "uuid"),
    stringField("langtextSourceField", "Langtext source field", false),
    dateField("langtextLinkedAt", "Langtext linked at", false),
    dateField("langtextOverriddenAt", "Langtext overridden at", false),
    stringField("kurzbeschreibungSourceEntity", "Kurzbeschreibung source entity", false),
    stringField("kurzbeschreibungSourceId", "Kurzbeschreibung source ID", false, "uuid"),
    stringField("kurzbeschreibungSourceField", "Kurzbeschreibung source field", false),
    dateField("kurzbeschreibungLinkedAt", "Kurzbeschreibung linked at", false),
    dateField("kurzbeschreibungOverriddenAt", "Kurzbeschreibung overridden at", false),
    stringField("warntextSourceEntity", "Warntext source entity", false),
    stringField("warntextSourceId", "Warntext source ID", false, "uuid"),
    stringField("warntextSourceField", "Warntext source field", false),
    dateField("warntextLinkedAt", "Warntext linked at", false),
    dateField("warntextOverriddenAt", "Warntext overridden at", false),
    stringField("description", "Description", false),
    stringField("articleGroupId", "Article group ID", false, "uuid"),
    stringField("taxClassId", "Tax class ID", false, "uuid"),
    stringField("baseUnitId", "Base unit ID", false, "uuid"),
    stringField("salesUnitId", "Sales unit ID", false, "uuid"),
    stringField("purchaseUnitId", "Purchase unit ID", false, "uuid"),
    dateField("archivedAt", "Archived at", false),
    customAttributesField,
    dateField("createdAt", "Created at", true),
    dateField("updatedAt", "Updated at", false),
    stringField("defaultWarehouseId", "Default warehouse ID", false, "uuid"),
    stringField("trackingMode", "Tracking mode", false),
    stringField("bomType", "BOM type", true, "code", "none"),
    booleanField("printPositionTexts", "Print position texts", false),
    stringField("primaryImageId", "Primary image ID", false, "uuid"),
  ],
  relations: {
    variants: { type: "many", target: "articleVariant", inverseField: "articleId" },
    bom: { type: "many", target: "articleBom", inverseField: "headerArticleId" },
  },
  behaviors: { softDelete: { strategy: "archivedAt", field: "archivedAt" } },
  constraints: [
    {
      id: "article.uniqueArticleNo",
      message: {
        en: "Article number must be unique within the tenant.",
        de: "Artikelnummer muss je Mandant eindeutig sein.",
      },
      severity: "error",
      fields: ["articleNo"],
    },
  ],
  tests: {
    crud: true,
    validationSmoke: true,
    fixture: { articleNo: "ART-001", name: "Sample Article" },
  },
});

export const articleVariantEntity = defineEntity({
  name: "articleVariant",
  pluralName: "articleVariants",
  label: { en: "Article variant", de: "Artikelvariante" },
  module: "masterdata",
  primaryKey: "variantId",
  tenantScoped: true,
  schemaVersion: 1,
  fields: [
    idField("variantId", "Variant ID"),
    tenantField,
    stringField("articleId", "Article", true, "uuid"),
    stringField("sku", "SKU", true, "code"),
    numberField("price", "Price", false, "currency"),
    dateField("archivedAt", "Archived at", false),
    dateField("createdAt", "Created at", true),
    dateField("updatedAt", "Updated at", false),
  ],
  relations: {
    article: { type: "one", target: "article", field: "articleId", required: true },
    inventoryItem: { type: "one", target: "inventoryItem", field: "variantId" },
  },
  constraints: [
    {
      id: "articleVariant.uniqueSku",
      message: {
        en: "SKU must be unique within the tenant.",
        de: "SKU muss je Mandant eindeutig sein.",
      },
      severity: "error",
      fields: ["sku"],
    },
  ],
  tests: { crud: true, validationSmoke: true, fixture: { sku: "SKU-001" } },
});

export const documentEntity = defineEntity({
  name: "document",
  pluralName: "documents",
  label: { en: "Document", de: "Beleg" },
  module: "sales",
  primaryKey: "documentId",
  tenantScoped: true,
  schemaVersion: 1,
  fields: [
    idField("documentId", "Document ID"),
    tenantField,
    stringField("companyId", "Company ID", true, "uuid"),
    stringField("documentType", "Type", true, "code"),
    stringField("documentDirection", "Direction", true),
    stringField("documentNo", "Document no.", true, "code"),
    stringField("status", "Status", true, "code", "draft"),
    stringField("customerId", "Customer", false, "uuid"),
    stringField("currencyId", "Currency", false),
    jsonField("printOptions", "Print options"),
    dateField("documentDate", "Document date", true),
    dateField("postingDate", "Posting date", false),
    numberField("totalNet", "Total net", false, "currency"),
    numberField("totalTax", "Total tax", false, "currency"),
    numberField("totalGross", "Total gross", false, "currency"),
    numberField("versionNo", "Version no.", true, "integer", 1),
    dateField("postedAt", "Posted at", false),
    stringField("postedBy", "Posted by", false),
    dateField("cancelledAt", "Cancelled at", false),
    stringField("stornoDocumentId", "Storno document ID", false, "uuid"),
    customAttributesField,
    dateField("createdAt", "Created at", true),
    dateField("updatedAt", "Updated at", false),
    stringField("transactionId", "Transaction ID", true, "uuid"),
    stringField("parentDocumentId", "Parent document ID", false, "uuid"),
    stringField("documentGroupId", "Document group ID", false, "uuid"),
    dateField("archivedAt", "Archived at", false),
    jsonField("billingAddress", "Billing address"),
    jsonField("deliveryAddress", "Delivery address"),
    stringField("deliveryAddressId", "Delivery address ID", false, "uuid"),
    stringField("noteText", "Note text", false),
    stringField("noteTextSourceEntity", "Note text source entity", false),
    stringField("noteTextSourceId", "Note text source ID", false, "uuid"),
    stringField("noteTextSourceField", "Note text source field", false),
    dateField("noteTextLinkedAt", "Note text linked at", false),
    dateField("noteTextOverriddenAt", "Note text overridden at", false),
    stringField("preText", "Pre text", false),
    stringField("preTextSourceEntity", "Pre text source entity", false),
    stringField("preTextSourceId", "Pre text source ID", false, "uuid"),
    stringField("preTextSourceField", "Pre text source field", false),
    dateField("preTextLinkedAt", "Pre text linked at", false),
    dateField("preTextOverriddenAt", "Pre text overridden at", false),
    stringField("postText", "Post text", false),
    stringField("postTextSourceEntity", "Post text source entity", false),
    stringField("postTextSourceId", "Post text source ID", false, "uuid"),
    stringField("postTextSourceField", "Post text source field", false),
    dateField("postTextLinkedAt", "Post text linked at", false),
    dateField("postTextOverriddenAt", "Post text overridden at", false),
    stringField("stornoText", "Storno text", false),
    stringField("stornoTextSourceEntity", "Storno text source entity", false),
    stringField("stornoTextSourceId", "Storno text source ID", false, "uuid"),
    stringField("stornoTextSourceField", "Storno text source field", false),
    dateField("stornoTextLinkedAt", "Storno text linked at", false),
    dateField("stornoTextOverriddenAt", "Storno text overridden at", false),
    stringField("paymentTermId", "Payment term ID", false, "uuid"),
    stringField("shippingMethodId", "Shipping method ID", false, "uuid"),
    stringField("documentTypeId", "Document type ID", false, "uuid"),
    stringField("warehouseId", "Warehouse ID", false, "uuid"),
    stringField("targetWarehouseId", "Target warehouse ID", false, "uuid"),
    booleanField("isPaid", "Is paid", false),
    dateField("paidAt", "Paid at", false),
    numberField("paidAmount", "Paid amount", false, "currency"),
    numberField("totalWeightKg", "Total weight kg", false, "decimal"),
    stringField("agentId", "Agent ID", false, "uuid"),
    numberField("commissionRate", "Commission rate", false, "decimal"),
  ],
  relations: {
    lines: { type: "many", target: "documentLine", inverseField: "documentId" },
    customer: { type: "one", target: "address", field: "customerId" },
  },
  behaviors: {
    softDelete: { strategy: "archivedAt", field: "archivedAt" },
    posting: { source: true, ledgerTarget: "postingEntry", immutableLedger: true },
    stateMachine: { field: "status", states: ["draft", "posted", "cancelled"] },
  },
  constraints: [
    {
      id: "document.uniqueCompanyDocumentNo",
      message: {
        en: "Document number must be unique per tenant and company.",
        de: "Belegnummer muss je Mandant und Firma eindeutig sein.",
      },
      severity: "error",
      fields: ["documentNo"],
    },
  ],
  tests: {
    crud: true,
    validationSmoke: true,
    fixture: { documentNo: "DOC-001", documentType: "N", status: "draft" },
  },
});

export const documentLineEntity = defineEntity({
  name: "documentLine",
  pluralName: "documentLines",
  label: { en: "Document line", de: "Belegzeile" },
  module: "sales",
  primaryKey: "documentLineId",
  tenantScoped: true,
  schemaVersion: 1,
  fields: [
    idField("documentLineId", "Document line ID"),
    tenantField,
    stringField("documentId", "Document", true, "uuid"),
    numberField("lineNo", "Line", true, "integer"),
    stringField("variantId", "Variant", false, "uuid"),
    numberField("quantity", "Quantity", true, "decimal"),
    numberField("netPrice", "Net price", true, "currency"),
    numberField("discountPercentage", "Discount percentage", false, "decimal"),
    stringField("taxCodeId", "Tax code ID", false, "uuid"),
    stringField("taxReason", "Tax reason", false),
    stringField("taxRuleId", "Tax rule ID", false, "uuid"),
    stringField("taxCountryCodeUsed", "Tax country code used", false),
    numberField("taxRateSnapshot", "Tax rate snapshot", false, "decimal"),
    numberField("taxAmount", "Tax amount", false, "currency"),
    numberField("lineTotalNet", "Line total net", false, "currency"),
    stringField("warehouseId", "Warehouse ID", false, "uuid"),
    stringField("costCenterId", "Cost center ID", false, "uuid"),
    stringField("movementType", "Movement type", false),
    stringField("lineType", "Line type", false),
    stringField("bomGroupId", "BOM group ID", false, "uuid"),
    dateField("archivedAt", "Archived at", false),
    dateField("createdAt", "Created at", true),
    dateField("updatedAt", "Updated at", false),
  ],
  relations: {
    document: { type: "one", target: "document", field: "documentId", required: true },
    variant: { type: "one", target: "articleVariant", field: "variantId" },
  },
  behaviors: { softDelete: { strategy: "archivedAt", field: "archivedAt" } },
  constraints: [
    {
      id: "documentLine.articleLineRequiresVariant",
      message: {
        en: "Article document lines require a variant.",
        de: "Artikel-Belegzeilen benoetigen eine Variante.",
      },
      severity: "error",
      fields: ["variantId"],
    },
  ],
  tests: { crud: true, validationSmoke: true, fixture: { lineNo: 1, quantity: 1, netPrice: 1 } },
});

export const inventoryMovementEntity = defineEntity({
  name: "inventoryMovement",
  pluralName: "inventoryMovements",
  label: { en: "Inventory movement", de: "Lagerbewegung" },
  module: "logistics",
  primaryKey: "inventoryMovementId",
  tenantScoped: true,
  schemaVersion: 1,
  fields: [
    idField("inventoryMovementId", "Inventory movement ID"),
    tenantField,
    stringField("inventoryItemId", "Inventory item", true, "uuid"),
    stringField("movementType", "Movement type", true, "code"),
    numberField("qtyDelta", "Quantity delta", false, "decimal"),
    dateField("createdAt", "Created at", true),
  ],
  behaviors: {
    posting: { source: false, ledgerTarget: "inventoryBalance", immutableLedger: true },
  },
  tests: { crud: false, validationSmoke: true },
});

export const postingBatchEntity = defineEntity({
  name: "postingBatch",
  pluralName: "postingBatches",
  label: { en: "Posting Batch", de: "Buchungscharge" },
  module: "accounting",
  primaryKey: "batchId",
  tenantScoped: true,
  schemaVersion: 1,
  fields: [
    idField("batchId", "Batch ID"),
    tenantField,
    stringField("documentId", "Document ID", false, "uuid"),
    dateField("postedAt", "Posted at", true),
    stringField("postedBy", "Posted by", true),
  ],
  behaviors: {},
  tests: { crud: true, validationSmoke: true },
});

export const postingEntryEntity = defineEntity({
  name: "postingEntry",
  pluralName: "postingEntries",
  label: { en: "Posting Entry", de: "Buchungssatz" },
  module: "accounting",
  primaryKey: "entryId",
  tenantScoped: true,
  schemaVersion: 1,
  fields: [
    idField("entryId", "Entry ID"),
    tenantField,
    stringField("batchId", "Batch ID", true, "uuid"),
    stringField("documentLineId", "Document line ID", false, "uuid"),
    stringField("variantId", "Variant ID", false, "uuid"),
    numberField("qtyDelta", "Quantity delta", false, "decimal"),
    numberField("amountDelta", "Amount delta", false, "currency"),
    stringField("accountCode", "Account code", false),
    stringField("entryType", "Entry type", true),
    stringField("description", "Description", false),
    dateField("createdAt", "Created at", true),
  ],
  behaviors: {},
  tests: { crud: true, validationSmoke: true },
});

export const coreEntityDefinitions = [
  addressEntity,
  articleEntity,
  articleVariantEntity,
  documentEntity,
  documentLineEntity,
  inventoryMovementEntity,
  postingBatchEntity,
  postingEntryEntity,
] as const;
