import type { AnyCapability } from "./core/types";

// Pure projection of the capability registry into a per-entity operation map.
// The generic TriView grid does POST/PATCH/DELETE on a *dynamic* entityName but
// capability ops are heterogeneous (upsert+archive vs create/update/delete, and
// the module prefix varies). This manifest is the runtime entity→op→key lookup
// the grid needs. It is intentionally STRINGS ONLY so the generated file can be
// imported from client bundles without dragging in handlers or Drizzle.

export interface EntityCapabilityEntry {
  /** The single module that owns this entity's capabilities. */
  module: string;
  /** operation name → full capability key (`${module}.${entityName}.${operation}`). */
  ops: Record<string, string>;
}

export type EntityCapabilityManifest = Record<string, EntityCapabilityEntry>;

// A few entities expose capabilities from more than one module: one module owns
// the generic CRUD surface, another adds a bespoke specialized op (e.g. the
// import flow's own `tenantConnector.list` alongside `system`'s full CRUD). The
// generic grid only wants the CRUD owner, so name it here explicitly; ops from
// other modules for that entity are intentionally left out of the manifest (they
// stay reachable by their full capability key).
const ENTITY_CANONICAL_MODULE: Record<string, string> = {
  tenantConnector: "system",
};

// Builds the manifest from the live registry. Throws on the two invariants the
// dynamic-entity grid relies on: an entity must resolve to exactly one module
// (directly or via ENTITY_CANONICAL_MODULE), and an operation name must be
// unique within that entity.
export function buildEntityCapabilityManifest(
  capabilities: readonly AnyCapability[],
): EntityCapabilityManifest {
  const manifest: EntityCapabilityManifest = {};
  for (const capability of capabilities) {
    const canonicalModule = ENTITY_CANONICAL_MODULE[capability.entityName];
    if (canonicalModule && capability.module !== canonicalModule) continue;

    let entry = manifest[capability.entityName];
    if (!entry) {
      entry = { module: capability.module, ops: {} };
      manifest[capability.entityName] = entry;
    } else if (entry.module !== capability.module) {
      throw new Error(
        `entity "${capability.entityName}" is claimed by modules "${entry.module}" and ` +
          `"${capability.module}"; add it to ENTITY_CANONICAL_MODULE to pick the CRUD owner`,
      );
    }
    if (entry.ops[capability.operation]) {
      throw new Error(
        `duplicate operation "${capability.operation}" for entity "${capability.entityName}"`,
      );
    }
    entry.ops[capability.operation] = capability.key;
  }
  return manifest;
}

// Deterministic source rendering (entities + ops sorted) so the generated file
// is stable and the drift test can compare byte-for-byte.
export function serializeEntityCapabilityManifest(manifest: EntityCapabilityManifest): string {
  const entityNames = Object.keys(manifest).sort();
  const entries = entityNames.map((entityName) => {
    const entry = manifest[entityName];
    const ops = Object.keys(entry.ops)
      .sort()
      .map((op) => `      ${JSON.stringify(op)}: ${JSON.stringify(entry.ops[op])},`)
      .join("\n");
    return [
      `  ${JSON.stringify(entityName)}: {`,
      `    module: ${JSON.stringify(entry.module)},`,
      `    ops: {`,
      ops,
      `    },`,
      `  },`,
    ].join("\n");
  });

  return [
    "// AUTO-GENERATED by `pnpm run generate:manifest` (packages/db) — do not edit by hand.",
    "// Strings only: safe to import from client bundles (no handlers, no Drizzle).",
    'import type { EntityCapabilityManifest } from "./manifest-build";',
    "",
    'export type { EntityCapabilityEntry, EntityCapabilityManifest } from "./manifest-build";',
    "",
    "export const entityCapabilityManifest: EntityCapabilityManifest = {",
    entries.join("\n"),
    "};",
    "",
  ].join("\n");
}
