// AUTO-GENERATED by `pnpm run generate:manifest` (packages/db) — do not edit by hand.
// Strings only: safe to import from client bundles (no handlers, no Drizzle).
import type { EntityCapabilityManifest } from "./manifest-build";

export type { EntityCapabilityEntry, EntityCapabilityManifest } from "./manifest-build";

export const entityCapabilityManifest: EntityCapabilityManifest = {
  "accountDeterminationRule": {
    module: "accounting",
    ops: {
      "create": "accounting.accountDeterminationRule.create",
      "get": "accounting.accountDeterminationRule.get",
      "list": "accounting.accountDeterminationRule.list",
      "update": "accounting.accountDeterminationRule.update",
    },
  },
  "accountingExportBatch": {
    module: "accounting",
    ops: {
      "buildRows": "accounting.accountingExportBatch.buildRows",
      "createBatch": "accounting.accountingExportBatch.createBatch",
      "csv": "accounting.accountingExportBatch.csv",
      "get": "accounting.accountingExportBatch.get",
      "list": "accounting.accountingExportBatch.list",
      "markExported": "accounting.accountingExportBatch.markExported",
      "rebuild": "accounting.accountingExportBatch.rebuild",
    },
  },
  "accountingExportRow": {
    module: "accounting",
    ops: {
      "create": "accounting.accountingExportRow.create",
      "get": "accounting.accountingExportRow.get",
      "list": "accounting.accountingExportRow.list",
      "update": "accounting.accountingExportRow.update",
    },
  },
  "address": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.address.archive",
      "get": "masterdata.address.get",
      "list": "masterdata.address.list",
      "search": "masterdata.address.search",
      "upsert": "masterdata.address.upsert",
    },
  },
  "addressCategory": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.addressCategory.archive",
      "create": "masterdata.addressCategory.create",
      "get": "masterdata.addressCategory.get",
      "list": "masterdata.addressCategory.list",
      "update": "masterdata.addressCategory.update",
    },
  },
  "addressContact": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.addressContact.archive",
      "create": "masterdata.addressContact.create",
      "get": "masterdata.addressContact.get",
      "list": "masterdata.addressContact.list",
      "search": "masterdata.addressContact.search",
      "update": "masterdata.addressContact.update",
    },
  },
  "article": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.article.archive",
      "get": "masterdata.article.get",
      "list": "masterdata.article.list",
      "search": "masterdata.article.search",
      "upsert": "masterdata.article.upsert",
    },
  },
  "articleBom": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.articleBom.archive",
      "create": "masterdata.articleBom.create",
      "get": "masterdata.articleBom.get",
      "list": "masterdata.articleBom.list",
      "update": "masterdata.articleBom.update",
    },
  },
  "articleCategory": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.articleCategory.archive",
      "create": "masterdata.articleCategory.create",
      "get": "masterdata.articleCategory.get",
      "list": "masterdata.articleCategory.list",
      "update": "masterdata.articleCategory.update",
    },
  },
  "articleGroup": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.articleGroup.archive",
      "get": "masterdata.articleGroup.get",
      "list": "masterdata.articleGroup.list",
      "upsert": "masterdata.articleGroup.upsert",
    },
  },
  "articleImage": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.articleImage.archive",
      "create": "masterdata.articleImage.create",
      "get": "masterdata.articleImage.get",
      "list": "masterdata.articleImage.list",
      "update": "masterdata.articleImage.update",
    },
  },
  "articleMedia": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.articleMedia.archive",
      "create": "masterdata.articleMedia.create",
      "get": "masterdata.articleMedia.get",
      "list": "masterdata.articleMedia.list",
      "update": "masterdata.articleMedia.update",
    },
  },
  "articleOption": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.articleOption.archive",
      "create": "masterdata.articleOption.create",
      "get": "masterdata.articleOption.get",
      "list": "masterdata.articleOption.list",
      "update": "masterdata.articleOption.update",
    },
  },
  "articleOptionValue": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.articleOptionValue.archive",
      "create": "masterdata.articleOptionValue.create",
      "get": "masterdata.articleOptionValue.get",
      "list": "masterdata.articleOptionValue.list",
      "update": "masterdata.articleOptionValue.update",
    },
  },
  "articleVariant": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.articleVariant.archive",
      "archiveBulk": "masterdata.articleVariant.archiveBulk",
      "copyVariantAxes": "masterdata.articleVariant.copyVariantAxes",
      "generateVariants": "masterdata.articleVariant.generateVariants",
      "get": "masterdata.articleVariant.get",
      "list": "masterdata.articleVariant.list",
      "previewVariants": "masterdata.articleVariant.previewVariants",
      "pricing": "masterdata.articleVariant.pricing",
      "update": "masterdata.articleVariant.update",
    },
  },
  "articleVariantOptionValue": {
    module: "masterdata",
    ops: {
      "create": "masterdata.articleVariantOptionValue.create",
      "delete": "masterdata.articleVariantOptionValue.delete",
      "get": "masterdata.articleVariantOptionValue.get",
      "list": "masterdata.articleVariantOptionValue.list",
    },
  },
  "articleVariantTemplate": {
    module: "masterdata",
    ops: {
      "applyToArticle": "masterdata.articleVariantTemplate.applyToArticle",
      "create": "masterdata.articleVariantTemplate.create",
      "get": "masterdata.articleVariantTemplate.get",
      "list": "masterdata.articleVariantTemplate.list",
      "update": "masterdata.articleVariantTemplate.update",
    },
  },
  "bankAccount": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.bankAccount.archive",
      "create": "masterdata.bankAccount.create",
      "get": "masterdata.bankAccount.get",
      "list": "masterdata.bankAccount.list",
      "update": "masterdata.bankAccount.update",
    },
  },
  "category": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.category.archive",
      "create": "masterdata.category.create",
      "get": "masterdata.category.get",
      "list": "masterdata.category.list",
      "update": "masterdata.category.update",
    },
  },
  "company": {
    module: "system",
    ops: {
      "archive": "system.company.archive",
      "create": "system.company.create",
      "get": "system.company.get",
      "list": "system.company.list",
      "update": "system.company.update",
    },
  },
  "connectorDefinition": {
    module: "system",
    ops: {
      "create": "system.connectorDefinition.create",
      "get": "system.connectorDefinition.get",
      "list": "system.connectorDefinition.list",
      "update": "system.connectorDefinition.update",
    },
  },
  "costCenter": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.costCenter.archive",
      "create": "masterdata.costCenter.create",
      "get": "masterdata.costCenter.get",
      "list": "masterdata.costCenter.list",
      "update": "masterdata.costCenter.update",
    },
  },
  "country": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.country.archive",
      "get": "masterdata.country.get",
      "list": "masterdata.country.list",
      "upsert": "masterdata.country.upsert",
    },
  },
  "currency": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.currency.archive",
      "get": "masterdata.currency.get",
      "list": "masterdata.currency.list",
      "upsert": "masterdata.currency.upsert",
    },
  },
  "deliveryAddress": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.deliveryAddress.archive",
      "create": "masterdata.deliveryAddress.create",
      "get": "masterdata.deliveryAddress.get",
      "list": "masterdata.deliveryAddress.list",
      "search": "masterdata.deliveryAddress.search",
      "update": "masterdata.deliveryAddress.update",
    },
  },
  "document": {
    module: "sales",
    ops: {
      "audit": "sales.document.audit",
      "convert": "sales.document.convert",
      "convertCandidates": "sales.document.convertCandidates",
      "create": "sales.document.create",
      "delete": "sales.document.delete",
      "delta": "sales.document.delta",
      "duplicate": "sales.document.duplicate",
      "duplicateCandidates": "sales.document.duplicateCandidates",
      "get": "sales.document.get",
      "list": "sales.document.list",
      "post": "sales.document.post",
      "pricing": "sales.document.pricing",
      "saveDraft": "sales.document.saveDraft",
      "shipment": "sales.document.shipment",
      "storno": "sales.document.storno",
      "tree": "sales.document.tree",
      "update": "sales.document.update",
    },
  },
  "documentGroup": {
    module: "sales",
    ops: {
      "get": "sales.documentGroup.get",
      "list": "sales.documentGroup.list",
    },
  },
  "documentLine": {
    module: "sales",
    ops: {
      "archive": "sales.documentLine.archive",
      "create": "sales.documentLine.create",
      "delta": "sales.documentLine.delta",
      "get": "sales.documentLine.get",
      "list": "sales.documentLine.list",
      "tracking": "sales.documentLine.tracking",
      "update": "sales.documentLine.update",
    },
  },
  "documentLineAllocation": {
    module: "sales",
    ops: {
      "create": "sales.documentLineAllocation.create",
      "get": "sales.documentLineAllocation.get",
      "list": "sales.documentLineAllocation.list",
      "update": "sales.documentLineAllocation.update",
    },
  },
  "documentLineTracking": {
    module: "sales",
    ops: {
      "add": "sales.documentLineTracking.add",
      "create": "sales.documentLineTracking.create",
      "get": "sales.documentLineTracking.get",
      "list": "sales.documentLineTracking.list",
      "remove": "sales.documentLineTracking.remove",
      "update": "sales.documentLineTracking.update",
    },
  },
  "documentShipment": {
    module: "logistics",
    ops: {
      "exportCsv": "logistics.documentShipment.exportCsv",
      "get": "logistics.documentShipment.get",
      "importTrackingCsv": "logistics.documentShipment.importTrackingCsv",
      "list": "logistics.documentShipment.list",
      "savePackages": "logistics.documentShipment.savePackages",
      "update": "logistics.documentShipment.update",
    },
  },
  "documentShipmentPackage": {
    module: "logistics",
    ops: {
      "get": "logistics.documentShipmentPackage.get",
      "list": "logistics.documentShipmentPackage.list",
      "update": "logistics.documentShipmentPackage.update",
    },
  },
  "documentType": {
    module: "sales",
    ops: {
      "get": "sales.documentType.get",
      "list": "sales.documentType.list",
    },
  },
  "emailAccount": {
    module: "communication",
    ops: {
      "list": "communication.emailAccount.list",
    },
  },
  "emailOutbox": {
    module: "communication",
    ops: {
      "composeDefaults": "communication.emailOutbox.composeDefaults",
      "confirmSend": "communication.emailOutbox.confirmSend",
      "prepareSend": "communication.emailOutbox.prepareSend",
    },
  },
  "emailTemplate": {
    module: "communication",
    ops: {
      "get": "communication.emailTemplate.get",
      "list": "communication.emailTemplate.list",
    },
  },
  "emailTemplateBinding": {
    module: "communication",
    ops: {
      "get": "communication.emailTemplateBinding.get",
      "list": "communication.emailTemplateBinding.list",
    },
  },
  "emailTemplateRenderLog": {
    module: "communication",
    ops: {
      "get": "communication.emailTemplateRenderLog.get",
      "list": "communication.emailTemplateRenderLog.list",
    },
  },
  "emailThread": {
    module: "communication",
    ops: {
      "archive": "communication.emailThread.archive",
      "get": "communication.emailThread.get",
      "link": "communication.emailThread.link",
      "list": "communication.emailThread.list",
      "markRead": "communication.emailThread.markRead",
    },
  },
  "fiscalPeriod": {
    module: "masterdata",
    ops: {
      "create": "masterdata.fiscalPeriod.create",
      "get": "masterdata.fiscalPeriod.get",
      "list": "masterdata.fiscalPeriod.list",
      "update": "masterdata.fiscalPeriod.update",
    },
  },
  "glAccount": {
    module: "accounting",
    ops: {
      "archive": "accounting.glAccount.archive",
      "create": "accounting.glAccount.create",
      "get": "accounting.glAccount.get",
      "list": "accounting.glAccount.list",
      "update": "accounting.glAccount.update",
    },
  },
  "importBatch": {
    module: "import",
    ops: {
      "approve": "import.importBatch.approve",
      "get": "import.importBatch.get",
      "list": "import.importBatch.list",
      "post": "import.importBatch.post",
      "upload": "import.importBatch.upload",
    },
  },
  "importProfile": {
    module: "import",
    ops: {
      "activateMapping": "import.importProfile.activateMapping",
      "create": "import.importProfile.create",
      "list": "import.importProfile.list",
      "mappings": "import.importProfile.mappings",
      "saveMappings": "import.importProfile.saveMappings",
      "update": "import.importProfile.update",
    },
  },
  "incoterm": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.incoterm.archive",
      "create": "masterdata.incoterm.create",
      "get": "masterdata.incoterm.get",
      "list": "masterdata.incoterm.list",
      "update": "masterdata.incoterm.update",
    },
  },
  "industry": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.industry.archive",
      "create": "masterdata.industry.create",
      "get": "masterdata.industry.get",
      "list": "masterdata.industry.list",
      "update": "masterdata.industry.update",
    },
  },
  "inventoryBalance": {
    module: "logistics",
    ops: {
      "create": "logistics.inventoryBalance.create",
      "get": "logistics.inventoryBalance.get",
      "list": "logistics.inventoryBalance.list",
      "update": "logistics.inventoryBalance.update",
    },
  },
  "inventoryItem": {
    module: "logistics",
    ops: {
      "create": "logistics.inventoryItem.create",
      "get": "logistics.inventoryItem.get",
      "list": "logistics.inventoryItem.list",
      "update": "logistics.inventoryItem.update",
    },
  },
  "inventoryMovement": {
    module: "logistics",
    ops: {
      "get": "logistics.inventoryMovement.get",
      "list": "logistics.inventoryMovement.list",
    },
  },
  "journalEntry": {
    module: "accounting",
    ops: {
      "create": "accounting.journalEntry.create",
      "get": "accounting.journalEntry.get",
      "list": "accounting.journalEntry.list",
      "update": "accounting.journalEntry.update",
    },
  },
  "journalLine": {
    module: "accounting",
    ops: {
      "create": "accounting.journalLine.create",
      "get": "accounting.journalLine.get",
      "list": "accounting.journalLine.list",
      "update": "accounting.journalLine.update",
    },
  },
  "modules": {
    module: "system",
    ops: {
      "create": "system.modules.create",
      "get": "system.modules.get",
      "list": "system.modules.list",
      "update": "system.modules.update",
    },
  },
  "numberSequence": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.numberSequence.archive",
      "create": "masterdata.numberSequence.create",
      "get": "masterdata.numberSequence.get",
      "list": "masterdata.numberSequence.list",
      "update": "masterdata.numberSequence.update",
    },
  },
  "organization": {
    module: "system",
    ops: {
      "archive": "system.organization.archive",
      "create": "system.organization.create",
      "get": "system.organization.get",
      "list": "system.organization.list",
      "update": "system.organization.update",
    },
  },
  "paymentTerm": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.paymentTerm.archive",
      "create": "masterdata.paymentTerm.create",
      "get": "masterdata.paymentTerm.get",
      "list": "masterdata.paymentTerm.list",
      "update": "masterdata.paymentTerm.update",
    },
  },
  "postalCode": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.postalCode.archive",
      "create": "masterdata.postalCode.create",
      "get": "masterdata.postalCode.get",
      "list": "masterdata.postalCode.list",
      "update": "masterdata.postalCode.update",
    },
  },
  "priceList": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.priceList.archive",
      "get": "masterdata.priceList.get",
      "list": "masterdata.priceList.list",
      "upsert": "masterdata.priceList.upsert",
    },
  },
  "priceListItem": {
    module: "masterdata",
    ops: {
      "create": "masterdata.priceListItem.create",
      "get": "masterdata.priceListItem.get",
      "list": "masterdata.priceListItem.list",
      "update": "masterdata.priceListItem.update",
    },
  },
  "productionOrder": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.productionOrder.archive",
      "create": "masterdata.productionOrder.create",
      "get": "masterdata.productionOrder.get",
      "list": "masterdata.productionOrder.list",
      "update": "masterdata.productionOrder.update",
    },
  },
  "serialNumber": {
    module: "logistics",
    ops: {
      "create": "logistics.serialNumber.create",
      "get": "logistics.serialNumber.get",
      "list": "logistics.serialNumber.list",
      "update": "logistics.serialNumber.update",
    },
  },
  "shippingMethod": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.shippingMethod.archive",
      "create": "masterdata.shippingMethod.create",
      "get": "masterdata.shippingMethod.get",
      "list": "masterdata.shippingMethod.list",
      "update": "masterdata.shippingMethod.update",
    },
  },
  "systemSettings": {
    module: "system",
    ops: {
      "create": "system.systemSettings.create",
      "get": "system.systemSettings.get",
      "list": "system.systemSettings.list",
      "update": "system.systemSettings.update",
    },
  },
  "taxClass": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.taxClass.archive",
      "create": "masterdata.taxClass.create",
      "get": "masterdata.taxClass.get",
      "list": "masterdata.taxClass.list",
      "update": "masterdata.taxClass.update",
    },
  },
  "taxCode": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.taxCode.archive",
      "create": "masterdata.taxCode.create",
      "get": "masterdata.taxCode.get",
      "list": "masterdata.taxCode.list",
      "update": "masterdata.taxCode.update",
    },
  },
  "taxRule": {
    module: "masterdata",
    ops: {
      "create": "masterdata.taxRule.create",
      "get": "masterdata.taxRule.get",
      "list": "masterdata.taxRule.list",
      "update": "masterdata.taxRule.update",
    },
  },
  "tenant": {
    module: "system",
    ops: {
      "archive": "system.tenant.archive",
      "create": "system.tenant.create",
      "get": "system.tenant.get",
      "list": "system.tenant.list",
      "update": "system.tenant.update",
    },
  },
  "tenantConnector": {
    module: "system",
    ops: {
      "archive": "system.tenantConnector.archive",
      "create": "system.tenantConnector.create",
      "get": "system.tenantConnector.get",
      "list": "system.tenantConnector.list",
      "update": "system.tenantConnector.update",
    },
  },
  "tenantConnectorMapping": {
    module: "system",
    ops: {
      "create": "system.tenantConnectorMapping.create",
      "get": "system.tenantConnectorMapping.get",
      "list": "system.tenantConnectorMapping.list",
      "update": "system.tenantConnectorMapping.update",
    },
  },
  "tenantFields": {
    module: "system",
    ops: {
      "archive": "system.tenantFields.archive",
      "create": "system.tenantFields.create",
      "get": "system.tenantFields.get",
      "list": "system.tenantFields.list",
      "update": "system.tenantFields.update",
    },
  },
  "tenantGroups": {
    module: "system",
    ops: {
      "create": "system.tenantGroups.create",
      "get": "system.tenantGroups.get",
      "list": "system.tenantGroups.list",
      "update": "system.tenantGroups.update",
    },
  },
  "tenantLayouts": {
    module: "system",
    ops: {
      "create": "system.tenantLayouts.create",
      "get": "system.tenantLayouts.get",
      "list": "system.tenantLayouts.list",
      "update": "system.tenantLayouts.update",
    },
  },
  "tenantLlmConfig": {
    module: "system",
    ops: {
      "create": "system.tenantLlmConfig.create",
      "get": "system.tenantLlmConfig.get",
      "list": "system.tenantLlmConfig.list",
      "update": "system.tenantLlmConfig.update",
    },
  },
  "tenantRules": {
    module: "system",
    ops: {
      "create": "system.tenantRules.create",
      "get": "system.tenantRules.get",
      "list": "system.tenantRules.list",
      "update": "system.tenantRules.update",
    },
  },
  "unit": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.unit.archive",
      "get": "masterdata.unit.get",
      "list": "masterdata.unit.list",
      "upsert": "masterdata.unit.upsert",
    },
  },
  "userTenant": {
    module: "system",
    ops: {
      "create": "system.userTenant.create",
      "get": "system.userTenant.get",
      "list": "system.userTenant.list",
      "update": "system.userTenant.update",
    },
  },
  "warehouse": {
    module: "masterdata",
    ops: {
      "archive": "masterdata.warehouse.archive",
      "create": "masterdata.warehouse.create",
      "get": "masterdata.warehouse.get",
      "list": "masterdata.warehouse.list",
      "update": "masterdata.warehouse.update",
    },
  },
};
