import type { AnyCapability } from "./core/types";

// Helper to capitalize first letter
const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export function buildAndSerializeClientSdk(capabilities: readonly AnyCapability[]): string {
  // Group by module, then by entityName
  const tree: Record<string, Record<string, Array<{ key: string; operation: string; kind: string }>>> = {};

  for (const cap of capabilities) {
    const mod = cap.module;
    const entity = cap.entityName;
    if (!tree[mod]) tree[mod] = {};
    if (!tree[mod][entity]) tree[mod][entity] = [];
    tree[mod][entity].push({
      key: cap.key,
      operation: cap.operation,
      kind: cap.kind,
    });
  }

  let code = `// AUTO-GENERATED by \`pnpm run generate:sdk\` (packages/db) — do not edit by hand.
import { capability } from "#/server-fns/capabilities";
import { useCapabilityQuery, useCapabilityMutation } from "#/queries/capability";
import type { CapabilityInput, CapabilityOutput } from "@repo/db/capabilities";
import type { UseQueryOptions } from "@tanstack/react-query";

export const sdk = {
`;

  // Sort modules for deterministic output
  const sortedModules = Object.keys(tree).sort();
  for (const mod of sortedModules) {
    code += `  ${mod}: {\n`;
    const sortedEntities = Object.keys(tree[mod]).sort();
    for (const entity of sortedEntities) {
      code += `    ${entity}: {\n`;
      // Sort operations for deterministic output
      const sortedOps = tree[mod][entity].sort((a, b) => a.operation.localeCompare(b.operation));
      for (const op of sortedOps) {
        const capOp = capitalize(op.operation);
        code += `      ${op.operation}: capability("${op.key}"),\n`;
        if (op.kind === "read") {
          code += `      use${capOp}: (\n`;
          code += `        input: CapabilityInput<"${op.key}">,\n`;
          code += `        options?: Omit<UseQueryOptions<CapabilityOutput<"${op.key}">, Error, CapabilityOutput<"${op.key}">>, "queryKey" | "queryFn">\n`;
          code += `      ) => useCapabilityQuery("${op.key}", input, options),\n`;
        } else {
          code += `      use${capOp}: (\n`;
          code += `        options?: {\n`;
          code += `          dryRun?: boolean;\n`;
          code += `          onSuccess?: (data: CapabilityOutput<"${op.key}">) => void;\n`;
          code += `          onError?: (error: unknown) => void;\n`;
          code += `        }\n`;
          code += `      ) => useCapabilityMutation("${op.key}", options),\n`;
        }
      }
      code += `    },\n`;
    }
    code += `  },\n`;
  }

  code += `};\n`;
  return code;
}
