// @ts-nocheck
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const uiDir = path.resolve(__dirname, "..");
const distComponentsDir = path.join(uiDir, "dist", "components");
const workspaceRoot = path.resolve(uiDir, "..", "..");
const agentsDir = path.join(workspaceRoot, ".agents");
const outputFile = path.join(agentsDir, "ui-components.md");

async function generate() {
  console.log("Generating UI components documentation...");

  let markdown = "# UI Components Reference\n\n";
  markdown +=
    "> **Note:** This document is auto-generated by `packages/ui/scripts/generate-ui-docs.ts`. Do not edit manually.\n\n";
  markdown +=
    "This file contains the TypeScript declarations for the `@repo/ui` component library. Read this file to understand component APIs, props, and generic capabilities.\n\n";

  try {
    const files = await fs.readdir(distComponentsDir);

    for (const file of files) {
      if (!file.endsWith(".d.ts")) continue;

      const componentName = file.replace(".d.ts", "");
      const filePath = path.join(distComponentsDir, file);
      const content = await fs.readFile(filePath, "utf-8");

      // Skip empty or purely export-only files without much substance to keep it clean
      if (content.trim().length < 20) continue;

      markdown += `## ${componentName}\n\n\`\`\`typescript\n${content.trim()}\n\`\`\`\n\n`;
    }

    await fs.mkdir(agentsDir, { recursive: true });
    await fs.writeFile(outputFile, markdown, "utf-8");
    console.log(`Successfully generated documentation at .agents/ui-components.md`);
  } catch (err) {
    console.error("Failed to generate UI docs:", err);
    process.exit(1);
  }
}

generate();
